version: "3"

services:
  lions-auth:
    build: .
    environment:
      - NODE_ENV
      - PORT=3000
    ports:
      - 3000:3000
    networks:
      - lions_network

networks:
  lions_network:
    external: true
